Skip to content
Search or jump to…
Pulls
Issues
Marketplace
Explore
 
@CharlieAbraham 
turntabl-sentiment-analysis
/
sentiment-service
Private
Code
Issues
Pull requests
1
Actions
Projects
Security
Insights
maven.yml
Java CI with Maven #11
Summary
Billable time
Workflow file
Jobs
build
Workflow file for this run
.github/workflows/maven.yml at 30b3dd0

name: Java CI with Maven

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15          
    - name: Build with Maven
      run: mvn -B package --file pom.xml

